// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgyGct9M1DLOa1hRAhB-YWA6ilrJA4QKk',
    appId: '1:44694107862:web:e72034965d9701dd6dfb77',
    messagingSenderId: '44694107862',
    projectId: 'fantahealth-1f00b',
    authDomain: 'fantahealth-1f00b.firebaseapp.com',
    storageBucket: 'fantahealth-1f00b.appspot.com',
    measurementId: 'G-QTEK35YRQD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfW_30eH32shdAm2gZzocSRYVzBamElSA',
    appId: '1:44694107862:android:47740c898f8b16206dfb77',
    messagingSenderId: '44694107862',
    projectId: 'fantahealth-1f00b',
    storageBucket: 'fantahealth-1f00b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXjr1U0A8KdYNQ63vZJb1YYE-has2ysCs',
    appId: '1:44694107862:ios:a0a563bef9d3a28b6dfb77',
    messagingSenderId: '44694107862',
    projectId: 'fantahealth-1f00b',
    storageBucket: 'fantahealth-1f00b.appspot.com',
    iosClientId: '44694107862-qt0l9qc6f2r33fb4esvq455688b97hj1.apps.googleusercontent.com',
    iosBundleId: 'com.fantasapp.purpleFilter.prod',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXjr1U0A8KdYNQ63vZJb1YYE-has2ysCs',
    appId: '1:44694107862:ios:6a5d2645e7566a956dfb77',
    messagingSenderId: '44694107862',
    projectId: 'fantahealth-1f00b',
    storageBucket: 'fantahealth-1f00b.appspot.com',
    iosClientId: '44694107862-aqp24c0a4kgipc5euooao9qd537q8qdj.apps.googleusercontent.com',
    iosBundleId: 'com.example.purpleFilter',
  );
}
